### ISSUE TITLE
Sphinx build directory

### ISSUE THREAD

**Issue by claudioperez** [NHERI-SimCenter/SimCenterDocumentation#106]
The `make.bat` file uses the `_build/` folder as its build directory, whereas `Makefile` is using `./web`. This is making it so that building from windows is creating output in a different location than building from a Unix-y system. Is this intended?

**Comment by fmckenna** [comment]
Does not matter .. files moved elsewhere later

**Comment by fmckenna** [comment]
All,

Tomorrow we will be programming in C and using TACC Frontera resource:
https://www.tacc.utexas.edu/systems/frontera to do so. With that in mind I
need to ensure that you can perform the exercises. This will require that
you can login to TACC. Logging in requires ssh and an app. The app, TACC
TOKEN: https://portal.tacc.utexas.edu/tutorials/multifactor-authentication
 must be installed on an Anroid or iOS device and set up. Instructions for
setting up are on page just provided.

TACC has also created an account for you. You will use the same login and
password as your DESIGNSAFE account. Before tomorrow can you perform
(replacing with your own appropriate login id's) the following::

1) Install TACC TOKEN on your phone.
2) Ensure you can login to TACC. To login to TACC from a terminal or
powershell type the following 3 things:

A) ssh YOUR-DESIGNSAGE-USERNAME@frontera.tacc.utexas.edu

this will prompt for your password, and then a TOKEN. Start the TACC TOKEN
APP, every 30seconds or so it shows a new token (6 numbers), enter the
current one.

B) this should log you on and after some introductions will leave you in a
linux terminal. Type the following there:

git clone  https://github.com/YOUR-GITHUB-USERNAME/SimCenterBootcamp2020.git

C) Now that you have cloned your repo, exit by typing:
exit


If you have problems with your password when logging in let me know (we did
not receive a login name from everybody)

thanks
frank
